version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging in to Amazon ECR..
       - pip install awscli --upgrade --user
       - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - make docker-build
        - make docker-tag
  post_build:
    commands:
       - echo Build completed on `date`
       - echo Pushing the Docker image...
       - make docker-push
